apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api-conversao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: brenopolisello/api-conversao-breno:v3
          ports:
          - containerPort: 8080
        